base-org/onchainsummer.xyz

README.md

Adds an image that will render.

Fix image in README

---

src/config/partners/anotherblock.ts
src/config/partners/fwb-bonfire.ts
src/config/partners/showtime.ts
src/config/partners/stand-with-crypto.ts

Update descriptions for partners
- Stand with Crypto
- Bonfire
- anotherblock
- showtime

Update descriptions for partners

---

src/config/partners/fwb.ts

chore: cross mint correction

---

src/components/WalletDialog/WalletContent.tsx

fix: base goerli

---

src/components/MintDialog/pages/Bridge/Bridge.tsx

fix: rounding on bridge

---

src/components/MintDialog/MintDialog.tsx
src/components/MintDialog/elements/Layout.tsx
src/components/Share/Share.tsx

- Fix confirmed modal spacing, close button, and twitter -> x
- This PR addresses two Mint Modal related P0 tickets: 
1. https://www.notion.so/lazertechnologies/72fceb443e3842debb9139a62d4ec37a?v=8331767752974fcdae4d0866e80975d0&p=5b7dd786f622465483a3af442f84ce03&pm=s
2. https://www.notion.so/lazertechnologies/72fceb443e3842debb9139a62d4ec37a?v=8331767752974fcdae4d0866e80975d0&p=46474161aaf14ec1aa881aa2c910e666&pm=s
- `ENV_VAR=`

chore: fix confirmed modal

---

src/components/MintDialog/elements/useBridge.tsx
src/utils/analytics.ts

feat: add bridge analytics

---

generated/tweets.ts
package.json
scripts/generateHighlightedTweets.js
src/utils/getTweets.ts

reverted tweets to static files instead of caching

chore: reverted tweets to static file instead of caching

---

src/app/layout.tsx

chore: remove cca

---

src/components/NFTAsset/NFTAsset.tsx
src/components/PartnerHero/PartnerHero.tsx
src/components/TweetCard/TweetCard.tsx

Change hero NFT videos to auto play while muted, but no other videos
- `ENV_VAR=`

chore: autoplay + mute hero video but not tweet

---

public/init_cca.js
src/app/layout.tsx

fix: cca fix 

---

src/config/partners/parallel.ts

fix: parallel creator address

---

src/components/MintDialog/MintDialog.tsx
src/components/MintDialog/pages/Bridge/Bridge.tsx
src/components/MintDialog/pages/Bridge/Bridging.tsx
src/components/MintDialog/pages/Bridge/NotStarted.tsx
src/components/MintDialog/pages/InsufficientFunds/usePollBalance.ts
src/utils/useBalances.ts
src/utils/useMintThresholds.ts

Send to insufficient funds screen if balance not enough
- `ENV_VAR=`

fix: Show insufficient balance screen if total price exceeds L2 balance

---

package.json
src/app/globals.css
src/app/page.tsx
yarn.lock

This PR fixes the scroll behaviour for anchor tags by updating to the latest version of nextjs
[Notion Ticket](https://www.notion.so/lazertechnologies/Fix-drops-anchor-a7f443f8f6764d12bd5cd637b2a41c31)

fix: update to latest next version with scroll fix

---

src/app/error.tsx
src/app/global-error.tsx
src/utils/analytics.ts
src/utils/useLogEvent.ts

chore: add error boundary

---

src/components/DropCard/DropCard.tsx
src/components/PartnerHero/PartnerHero.tsx

- Evenly space drop cards with long names, line clamp at 2 lines
- `ENV_VAR=`

chore: evenly space drop cards with long names

---

src/components/WalletDialog/WalletContent.tsx

fix: use contextual l2

---

src/components/NFTAsset/NFTAsset.tsx

This PR fixes z-index on the drop card videos so that videos are interactive

fix: allow videos to play over nft drop link

---

src/components/DropCard/DropCard.tsx

fix: unlock magic button on dropcard

---

src/app/page.tsx

chore: removed hide scroll

---

src/config/partners/coke.ts

fix: use opensea

---

src/app/[slug]/page.tsx

chore: lowercasing when matching slug

---

src/app/[slug]/page.tsx
src/app/page.tsx
src/app/trending/page.tsx
src/components/DropCard/DropCard.tsx
src/components/MintDialog/Context/Context.ts
src/components/MintDialog/elements/NativeMintButton.tsx
src/components/MintDialog/pages/NativeMint/NativeMint.tsx
src/components/PartnerHero/PartnerHero.tsx
src/config/partners/stand-with-crypto.ts
src/config/partners/types.ts

- Added a dataSuffix key to drop schema which is optional
- `label` key is a markdown-friendly string value to render a checkbox for the dataSuffix question
- `value` is the HEX value that is supposed to be used when the check box is set to true
- Prop drilled dropDataSuffix down to NativeMint component where the component is rendered optionally if the dataSuffix object is not undefined or null
- The check box has no validation
- Upon change of the checkbox, the dataSuffic prop is updated

chore: added data suffix config and checkbox

---

src/app/[slug]/page.tsx
src/app/page.tsx
src/components/DropCard/DropCard.tsx
src/components/ExternalDrop/ExternalDrop.tsx
src/config/partners/stand-with-crypto.ts
src/config/partners/types.ts

feat: custom button text on external drop cards

---

src/config/partners/stand-with-crypto.ts

chore: updated arweave digest ID

---

src/components/MintDialog/elements/CitzienshipCheckbox.tsx
src/config/partners/stand-with-crypto.ts

feat: update checkbox label

---

src/components/MintDialog/MintDialog.tsx
src/components/MintDialog/elements/CitzienshipCheckbox.tsx

This PR fixes max height for the mint dialog

fix: max-h for mint dialog, citizenship margin

---

src/components/MintDialog/MintDialog.tsx

Intentionally exclude page from dep array

fix: exclude page from dep array

---

public/partners/rainbow-wallet/banner-icon.svg
src/config/partners/blackbird.ts
src/config/partners/fwb.ts
src/config/partners/highlight.ts
src/config/partners/nestcoin.ts
src/config/partners/rainbow-wallet.ts
src/config/partners/zora.ts

chore: updated description field

---

.codeflow.yml

This should help with the double review problem for internal deployments

Require verified commits

---

src/app/api/arweave/route.ts

error logging and response to arweave endpoint

chore: error logging and response to arweave endpoint

---

src/app/[slug]/page.tsx
src/app/page.tsx
src/components/DropCard/DropCard.tsx

- Added drop description to DropCard component below address pill 
- `ENV_VAR=`

feat: add descriptions to drop cards

---

src/components/DropCard/DropCard.tsx
src/config/partners/zora.ts

- Changed asset container in drop card to have full height and align items in the center with a black background and consistently rounded corners.

chore: square drop card assets

---

src/app/trending/page.tsx
src/components/MintDialog/types.ts
src/utils/externalCbnftUrl.ts

Open Coke drops on CBNFT
You can see the URL i'm hovering over on the bottom of browser

Open Coke drops on CBNFT

---

src/components/Footer/Footer.tsx

- added privacy policy link to the community section of the footer
- `ENV_VAR=`

chore: added privacy policy link to community section of the footer

---

.codeflow.yml
Dockerfile.cdnsync
cdnsync.js

Add script + build for syncing large files from a Google Drive folder to our CDN S3 bucket.

Add cdnsync script

---

generated/tweets.ts
src/components/TweetCard/TweetCard.tsx

| Before | After |
| ------ | ------ |
| ![image](https://github.com/base-org/onchainsummer.xyz/assets/6590647/36bd60cc-b944-44c2-b5e9-193d1c07dd94) | ![image](https://github.com/base-org/onchainsummer.xyz/assets/6590647/7dfcf073-6dad-4084-ba4a-c01f6d09dd4b) |
- `ENV_VAR=`

chore: tweet url unfurl

---

src/config/partners/zora.ts

chore: reverted zora links

---

src/config/partners/pixelmon.ts

chore: update pixelmon copy

---

src/config/partners/pixelmon.ts

Updated Shopify store link for Pixelmon
- `ENV_VAR=`

chore: update Pixelmon link

---

src/app/page.tsx
src/components/Trending/Trending.tsx

chore: hide mint for fun if no collections

---

src/components/ConnectDialog/ConnectDialog.tsx
src/components/Navbar/Mobile.tsx

fix: cb two tap connect

---

src/config/partners/mirror-wellness.ts

- updated mirror wellness info to match GTM tracker
- `ENV_VAR=`

chore: updated mirror wellness info to match GTM tracker

---

src/app/api/partners/[slug]/audit/route.ts

Added audit route for partner config check, it checks the following things:
- Empty values on partner and drop level
- Date ranges are valid
- Duplication of data between various partners
- Valid Arweave digest by fetching Arweave from the API
- Valid Twitter handle by fetching Twitter user info
- Valid creator address by fetching ENS
- Valid contract address by reading the contract name from the chain
- https schema check partner url
- `ENV_VAR=`
FWB test
Pixelmon test
Showtime test

chore: partner audit endpoint

---

src/config/partners/showtime.ts

fix: showtime titles

---

src/app/[slug]/page.tsx
src/app/page.tsx
src/components/Tabs/Tabs.tsx
tailwind.config.js

This PR aligns bg and drop shadow on the sections between landing and /partner pages

feat: section bg and drop-shadow alignment

---

generated/tweets.ts

feat: add new tweets

---

src/app/api/partners/[slug]/audit/route.ts

- If ENS is null report as error
- If description starts with quotes, flag an error
- Only check duplication for values that are not null
- `ENV_VAR=`

chore: small optimizations

---

src/config/partners/mirror-wellness.ts

chore: mirror wellness config update

---

src/config/partners/coinbase.ts

- Updated partner colour to Coinbase blue
- Updated wallet drop card link to: https://go.cb-w.com/buyAndMint

chore: update Coinbase color and wallet link

---

src/app/[slug]/page.tsx
src/app/page.tsx
src/components/AddressPill/AddressPill.tsx
src/components/Card/Card.tsx
src/components/DropCard/DropCard.tsx
src/components/DropCard/DropCardList.tsx
src/components/Trending/Trending.tsx
src/components/TweetCard/TweetCard.tsx

This PR resolves the issue with DropCard layout and title height/address pills lining up

Drop card refactor

---

src/components/MintButton/MintButton.tsx
src/components/MintButton/useValidate.tsx

Show the collect button when a mint is `minted out`

feat: show collect button when mint minted out

---

generated/tweets.ts
src/components/TweetCard/TweetCard.tsx

chore: update tweets

---

generated/arweave.ts

Generated Arweaves so we have a fallback if it's not working (for Mirror)

fix: update fallbacks for Arweave

---

generated/tweets.ts
src/components/TweetCard/TweetCard.tsx

- Updated tweets and changed the character limit
- Temporarily removed the regex / character replacing logic until we sort out the right way to do this (the handles are being replaced right now if you don't remove this)

chore: update 08-20 Tweets and char limit

---

next.config.js

fix: allow assets from onchainsummer domain

---

src/config/partners/manifold.ts

- updated names and descriptions for Manifold

chore: Manifold update twitter handle, descriptions, names

---

src/components/DropCard/DropCard.tsx
src/components/NFTAsset/NFTAsset.tsx
src/config/partners/highlight.ts

Highlight config and changes from #351

feat: highlight config and drop card treatment

---

generated/tweets.ts

chore: update 08-22 tweets

---

src/app/providers.tsx
src/components/ConnectDialog/ConnectDialog.tsx
src/components/DesiredNetworkContext/DesiredNetworkContext.tsx
src/components/DesiredNetworkContext/useDesiredNetworkContext.ts
src/components/MintDialog/MintDialog.tsx
src/components/MintDialog/elements/useBridge.tsx
src/components/MintDialog/pages/Bridge/Bridge.tsx
src/components/MintDialog/pages/Bridge/NotStarted.tsx
src/utils/getIsCoinbaseBrowser.ts

This PR auto-switches user to the appropriate network.
It allows developers to control what the desired network is via the `DesiredNetworkContext` which can be switched between l2 and l1 - allowing for bridging.

feat: force user to switch to appropriate network

---

src/components/MintButton/MintButton.tsx
src/components/MintButton/useValidate.tsx
src/components/MintDialog/Context/Context.ts
src/components/MintDialog/elements/NativeMintButton.tsx
src/components/MintDialog/elements/Quantity.tsx

fix: persist max claimable

---

src/config/partners/fini.ts

Update fini upcoming drop description

fix: upcoming drop description for fini

---

Dockerfile

chore: add reservoir to docker

---

generated/tweets.ts
src/components/TweetCard/TweetCard.tsx

This PR updates the tweets and how height is managed for media

fix: manually add image to generated tweet, manage height for unfurl/media

---

src/app/api/partners/[slug]/audit/route.ts

Tweak error/warn details for aarweave audit

fix: aarweave validation tweaks

---

src/app/page.tsx

Hide the Article / Remaining Drops section if neither exist

fix: only render article/remaining drops section if one of those 2 exist

---

src/app/[slug]/page.tsx
src/app/page.tsx

This PR adds NFT Meta tags for the partner page's featured drop

feat: nft meta tags for partner pages

---

src/config/partners/atari.ts

feat: atari config review

---

src/config/partners/open-sea.ts

Opensea config review

---

src/config/partners/fwb-bonfire.ts

feat: bonfire config

---

src/config/partners/fini.ts

feat: fini config

---

generated/arweave.ts

Updated Arweave fallback (until Aug 24)

fix: update arweave fallback

---

src/app/page.tsx
src/config/partners/anotherblock.ts
src/config/partners/highlight.ts
src/config/partners/indelible.ts
src/config/partners/manifold.ts
src/config/partners/onboard.ts

Sequence order fix and new additions

Sequence update and fix

---

src/config/partners/atari.ts

Atari config updates
- description
- order of carousel mints
- adding interactive links

feat: atari description update, interact links, and order

---

generated/tweets.ts

feat: twitter updates for aug 25

---

src/config/partners/iskra.ts

- Updated main description (in upcoming drops)
- Added missing period in hero drop text
- Updated assets for all drops
- Added post-mint button and link (https://iskra.world/clashmon_reveal)

chore: update main desc, assets, and post-mint CTA

---

generated/tweets.ts

Updated first tweet in the list for 08-25

chore: more updates for tweets on 08-25

---

src/config/partners/oak.ts

feat: new oak assets and description

---

src/config/partners/iskra.ts

chore: update Iskra digest ID

---

src/config/partners/coinbase.ts

Updated Coinbase Wallet config with new links and descriptions

chore: update Coinbase config links and desc

---

generated/tweets.ts

chore: updates tweets for 08-26

---

src/config/community.ts

chore: update community grant dates

---

generated/tweets.ts

chore: updates tweets for 08-27

---

src/config/partners/iskra.ts

fix: updated iskra external link for first drop

---

src/components/MintDialog/pages/Bridge/NotStarted.tsx
src/config/partners/iskra.ts

- Remove Iskra Crossmint ID
- Don't show the Crossmint button in Bridging > Not Started

Disable iskra crossmint

---

generated/arweave.ts

Updating fallback content for arweave as of Aug 27 (i.e. Iskra publish)

chore: update fallback arweave content for Aug 27

---

src/components/MintDialog/MintDialog.tsx

Updated mint button copy for free mints

feat: update mint CTA copy for free mints

---

generated/tweets.ts

chore: updates tweets for 08-28

---

src/config/partners/oak.ts

Updated Oak config:
- Twitter handle
- Website URL

fix: corrected Oak website url and twitter handle

---

src/config/partners/fini.ts

chore: update fini config

---

src/config/partners/open-sea.ts

Updated one drop image for Opensea

chore: updated opensea second drop asset

---

generated/tweets.ts

chore: twitter updates for aug 30

---

generated/tweets.ts

feat: twitter updates for aug 31

---

generated/arweave.ts

Added Arweave content as of Aug 30

chore: update arweave fallback for Aug 30

---

src/config/partners/fini.ts

Added missing crossmint id for fini

chore: update fini crossmint id

---

src/config/partners/fini.ts

Updated spacing for Fini description

fix: update description spacing for fini

---

generated/tweets.ts
src/components/TweetCard/TweetCard.tsx

- Generated tweets
- Changed tweet card width to try and get 3 per row on desktop (for common resolutions)

Updated for 09-01 including 6 instead of 3

---

src/app/page.tsx
src/components/MintButton/MintButton.tsx
src/config/partners/fini.ts
src/config/partners/rainbow-wallet.ts

We shouldn't need the date filter anymore now that we can use reservoir collect
- `ENV_VAR=`

feat: remove date filter on active, ensure collect button shows

---

src/config/partners/parallel.ts

There was an error in the price being shown so partner asked us to remove
- `ENV_VAR=`

chore: do not show collect button for parallel

---

.codeflow.yml

Move notifications to separate channel

Move codeflow alerts to seperate channel

---

.husky/pre-commit
src/config/chain.ts

fix: it's currently unsupported to use "export *" in a client boundary
